# TransitFlow dbt Project
# Pattern: Semantic Interface - Unified Serving Layer

name: 'transitflow'
version: '1.0.0'
config-version: 2

profile: 'transitflow'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations
models:
  transitflow:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    dimensions:
      +materialized: table
      +schema: dimensions
    marts:
      +materialized: table
      +schema: marts

# Seed configurations: GTFS Static Data
# Explicit routing: each file gets its own explicit alias
seeds:
  transitflow:
    +schema: reference
    seed_stops:
      +alias: stops
    seed_lines:
      +alias: lines

# Test configurations
tests:
  +severity: error
  +store_failures: true

vars:
  on_time_threshold: 60
  delayed_threshold: 300
  max_delay_seconds: 7200
  min_delay_seconds: -3600
  scd_end_date: '2099-12-31 23:59:59'