# TransitFlow dbt Project
# Pattern: Semantic Interface - Unified Serving Layer
# UTC Lock and Alias-Free Lineage

name: 'transitflow'
version: '1.0.0'
config-version: 2

profile: 'transitflow'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  transitflow:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
    dimensions:
      +materialized: table
      +schema: dimensions
    marts:
      +materialized: table
      +schema: marts

# --- Seed configurations ---
seeds:
  transitflow:
    +schema: reference
    +quote_columns: false 

# --- Snapshot configurations ---
snapshots:
  transitflow:
    +target_schema: snapshots

tests:
  +severity: error
  +store_failures: true

vars:
  # Standardized names to match audited SQL logic
  on_time_threshold_seconds: 60
  late_threshold_seconds: 300
  max_delay_seconds: 7200
  min_delay_seconds: -3600
  scd_end_date: '2099-12-31 23:59:59'
  # Target Date: Dynamically injected for OCI/Cron runs
  target_date: "{{ env_var('DATE', run_started_at.strftime('%Y-%m-%d')) }}"