transitflow:
  target: dev
  outputs:
    dev:
      type: duckdb
      # No fallback: if the env_var is missing, dbt will rightfully crash
      path: '{{ env_var("DBT_DATABASE_PATH") }}'
      schema: main
      threads: 4