# dbt Connection Profiles
# NOTE: In production, use environment variables for credentials

transitflow:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '{{ env_var("DBT_DATABASE_PATH", "/tmp/transitflow.duckdb") }}'
      schema: main
      threads: 4
      
    # Delta Lake profile (requires dbt-delta plugin)
    # Uncomment when running with full Spark infrastructure
    # delta:
    #   type: spark
    #   method: thrift
    #   host: localhost
    #   port: 10000
    #   schema: transitflow
    #   threads: 4