version: 2

sources:
  - name: bronze
    description: "Raw telemetry and stop events from Spark Bronze"
    schema: bronze 
    tables:
      - name: enriched
      - name: stop_events

  - name: raw_lakehouse
    description: "Gold data produced by Spark Sink"
    database: "{{ env_var('POSTGRES_DB') }}" 
    schema: public # Matches Spark Sink location
    tables:
      - name: fct_stop_arrivals
        description: "Spark Gold Sink for Stop Performance"
        identifier: fct_stop_arrivals

      - name: fct_daily_performance
        description: "Daily KPIs for analytical reporting"
        identifier: fct_daily_performance
        loaded_at_field: ingestion_time 
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}