version: 2

sources:
  - name: bronze
    description: "Raw streaming data from Flink/Kafka"
    schema: bronze
    loaded_at_field: ingestion_time
    tables:
      - name: enriched
        description: "Enriched vehicle telemetry events"
      - name: stop_events
        description: "Raw stop arrival detections"

  - name: raw_lakehouse
    description: "Aggregated Gold data synced from MinIO by Spark"
    database: transit
    schema: public
    tables:
      - name: fct_stop_arrivals
        description: "Aggregated stop performance (Source for Marts)"
      - name: fct_daily_performance
        description: "Aggregated daily KPIs (Source for Marts)"

  - name: reference
    description: "Static reference data (GTFS)"
    schema: reference
    tables:
      - name: seed_stops
      - name: seed_lines