/*
    Staging model for stop arrival events.
    
    These events are ML training labels generated by Flink CEP.
    delay_at_arrival is the target variable for prediction.
*/

with source as (
    select * from {{ source('bronze', 'stop_events') }}
),

cleaned as (
    select
        -- Primary identifiers
        vehicle_id,
        stop_id,
        
        -- Timestamps
        arrival_time,
        to_timestamp(arrival_time / 1000) as arrival_timestamp,
        cast(date_trunc('day', to_timestamp(arrival_time / 1000)) as date) as arrival_date,
        
        -- ML target variable
        delay_at_arrival,
        
        -- Delay categorization (for analysis)
        case
            when abs(delay_at_arrival) <= {{ var('on_time_threshold') }} then 'on_time'
            when delay_at_arrival > {{ var('delayed_threshold') }} then 'delayed'
            when delay_at_arrival < -{{ var('delayed_threshold') }} then 'early'
            else 'slight_delay'
        end as delay_category,
        
        -- Other fields
        line_id,
        direction_id,
        dwell_time_ms,
        door_opened,
        latitude,
        longitude,
        
        -- Metadata
        kafka_partition,
        kafka_offset,
        ingestion_time,
        date as partition_date
        
    from source
    where 
        vehicle_id is not null
        and stop_id is not null
        and arrival_time is not null
        and delay_at_arrival is not null
        -- Filter unrealistic delays
        and delay_at_arrival between {{ var('min_delay_seconds') }} and {{ var('max_delay_seconds') }}
)

select * from cleaned